# Generated by Django 4.1 on 2022-08-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
